services:
  app:
    container_name: app
    image: app-dev
    build:
      context: .
    restart: "no"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - app-network
    entrypoint: "symfony serve" # Comment the entrypoint to disable the server auto start

networks:
  app-network:
    driver: bridge

volumes:
    db-data:
        driver: local
