services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: app-nginx
  #   ports:
  #     - "127.0.0.1:8000:80"
  #   volumes:
  #     - ./public/:/var/www/html
  #     - ./docker/nginx/local/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

  app:
    container_name: app
    image: app-dev
    build:
      context: .
    restart: "no"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - app-network

  # db:
  #   image: mysql:latest
  #   container_name: app-db
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: "no"
  #   environment:
  #     MYSQL_DATABASE: app-db
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_USER: app-user
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
    db-data:
        driver: local
