FROM php:8.3-fpm AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    git \
	acl \
	file \
	gettext \
	git \
	&& rm -rf /var/lib/apt/lists/*

RUN install-php-extensions @composer

WORKDIR /app
#VOLUME /app/var/

COPY . .

#RUN set -eux; \
#	mkdir -p var/cache var/log; \
#	composer dump-autoload --classmap-authoritative --no-dev; \
#	composer dump-env prod; \
#	composer run-script --no-dev post-install-cmd; \
#	chmod +x bin/console; sync;
